name:                multiplayer-connectfour
version:             0.1.0.0
github:              ""
license:             BSD3
author:              "Benjamin Schaden, Jakob Rosenblattl"
maintainer:          "benni.schaden@gmail.com"
copyright:           "Benjamin Schaden, Jakob Rosenblattl"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - matrix
    - universe-base
    - cereal
  default-extensions:
    - DeriveGeneric 


executables:
  server:
    main:                Main.hs
    source-dirs:         app/server
    ghc-options:
    - -Wall
    - -Werror
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -ferror-spans
    dependencies:
    - haskell-party
    - network
    - bytestring
    - stm
    - cereal
    - matrix
    - MissingH
    default-extensions:
    - DeriveGeneric 
    - DefaultSignatures

  client:
    main:                Main.hs
    source-dirs:         app/client
    ghc-options:
    - -Wall
    - -Werror
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -ferror-spans
    dependencies:
    - haskell-party
    - network
    - bytestring
    - stm
    - cereal
    - matrix
    - brick
    - vty
    - microlens
    - microlens-th
    - MissingH
    default-extensions:
    - DeriveGeneric 
    - DefaultSignatures

tests:
  haskell-party-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-party
